# Generated by Django 5.2.6 on 2025-09-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
        ('cursada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='alumno.alumno')),
                ('cursada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursada.cursada')),
            ],
        ),
    ]
