# Generated by Django 5.2.6 on 2025-09-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera'),
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
