# Generated by Django 5.2.6 on 2025-09-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
        ('materia', '0002_materia_carrera_materia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='carrera.carrera'),
        ),
    ]
