# Generated by Django 5.2.6 on 2025-09-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0002_materia_carrera_materia_codigo'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(blank=True, null=True)),
                ('cuatrimestre', models.IntegerField(blank=True, null=True)),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='materia.materia')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='profesor.profesor')),
            ],
        ),
    ]
