# Generated by Django 5.2.8 on 2025-11-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursada',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
