# Generated by Django 5.2.8 on 2025-11-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursada', '0002_alter_cursada_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursada',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
